// GENERATED by scripts/build.mjs — do not edit. Every lib/integrations/*.js (except _*.js)
// is a backend integration; add a file there and run `npm run build` to register it.
import aqara from './aqara.js';
import finnhub from './finnhub.js';
import spotify from './spotify.js';
import strava from './strava.js';
import todoist from './todoist.js';
import tomtom from './tomtom.js';

export default [aqara, finnhub, spotify, strava, todoist, tomtom];
